name: Publish (pypi prod)
# IMPORTANT NOTE: (see pypi guide)
# For security reasons, you must require manual approval on each run for the
# pypi environment.

on:
  release:
    types: [created]

env:
  PYTHON_VERSION_FOR_BUILD: 3.12
  POETRY_VERSION: "1.8.2"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 7

    steps:
      # Root path under $GITHUB_WORKSPACE
      - uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION_FOR_BUILD }}

      - name: Set up poetry (ubuntu one-shot)
        shell: bash
        run: |
          curl -sSL https://install.python-poetry.org | \
          python3 - --version ${{env.POETRY_VERSION}} \
          && echo "$HOME/.poetry/bin" >> $GITHUB_PATH

      - name: Build
        run: |
          poetry version $(git describe --tags --abbrev=0)
          poetry build
          
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: python-package-distributions
          path: dist/

  publish:
    # Only publish if current commit is tagged
    if: startsWith(github.ref, 'refs/tags/')
    needs:
    - build
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/tevec
    permissions:
      id-token: write # Mandatory for trusted publishing

    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v3
      with:
        name: python-package-distributions
        path: dist/
    - name: Publish to PyPI (test)
      uses: pypa/gh-action-pypi-publish@release/v1

  # TODO: add sigstore step
  # See here for reference:
  #     https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/
